variables:
  runner: '.ci/jenkins/runner.py'
  module: '"conans.test"'
  api_conf: 'v1'
  flavor: 'no_revisions'
  num_cores: 4
  workdir: "."
  sourcedir: "."

resources:
  containers:
  - container: conan_tests
    image: lasote/conantests_azure

strategy:
  matrix:
    linux_py2:
      pyver: py27
    linux_py3:
      pyver: py36

jobs:
- job: Linux py27
  pool:
    vmImage: 'ubuntu-16.04'
  container: conan_tests
  steps:
  - script: python $(runner) $(module) $(pyver) $(sourcedir) $(workdir) -e rest_api $(numcores) --server_api=$(api_conf) -f $(flavor)

- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - script: python $(runner) $(module) $(pyver) $(sourcedir) $(workdir) -e rest_api $(numcores) --server_api=$(api_conf) -f $(flavor)

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: python $(runner) $(module) $(pyver) $(sourcedir) $(workdir) -e rest_api $(numcores) --server_api=$(api_conf) -f $(flavor)


