variables:
  runner: .ci/jenkins/runner.py
  module: '"conans.test"'
  api_conf: v1
  flavor: no_revisions
  num_cores: 4
  workdir: .
  sourcedir: $(Build.Repository.LocalPath)

resources:
  containers:
  - container: conan_tests
    image: lasote/conan_tests_azure


jobs:

- template: .ci/azure/build_linux.yml
  parameters:
    name: LinuxPy27
    pyver: py27

- template: .ci/azure/build_linux.yml
  parameters:
    name: LinuxPy36
    pyver: py36

- template: .ci/azure/build_macos.yml
  parameters:
    name: Macospy37
    pyver: py37


- job: Windows
  variables:
    pyver: py27
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: python $(runner) $(module) $(pyver) $(sourcedir) $(workdir) -e rest_api --num_cores=$(num_cores) --server_api=$(api_conf) -f $(flavor)
