# File: jobs/build.yml

parameters:
  pyver: ''

jobs:
- job: Linux${{ parameters.name }}
  timeoutInMinutes: 0
  cancelTimeoutInMinutes: 0
  variables:
    num_cores: 8
    pyver: ${{ parameters.pyver }}
  pool:
    vmImage: 'ubuntu-16.04'
  container: conan_tests
  steps:
  - script: python $(runner) $(module) $(pyver) $(sourcedir) $(workdir) -e rest_api --num_cores=$(num_cores) --server_api=$(api_conf) -f $(flavor)
  - script: python $(runner) conans.test.remote.rest_api_test $(pyver) $(workdir) /tmp
