# File: jobs/build.yml

parameters:
  pyver: ''

jobs:
- job: ${{ format('Windows{0}', parameters.pyver) }}
  timeoutInMinutes: 0
  cancelTimeoutInMinutes: 0
  variables:
    pyver: ${{ parameters.pyver }}
    num_cores: 8
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      ${{ if eq(parameters.pyver, 'py36') }}:
        versionSpec: '3.6'
      ${{ if eq(parameters.pyver, 'py34') }}:
        versionSpec: '3.4'
      ${{ if eq(parameters.pyver, 'py27') }}:
        versionSpec: '2.7'
      addToPath: true
  - script: pip install virtualenv
  - script: python --version
    displayName: Show python version
  - script: choco install cmake --version 3.7.2 -y
  - script: python $(runner) $(module) $(pyver) $(sourcedir) $(workdir) -e rest_api --num_cores=$(num_cores) --server_api=$(api_conf) -f $(flavor)
    displayName: Regular tests
    env:
      CONAN_RECIPE_LINTER: 'False'
  - script: python $(runner) conans.test.remote.rest_api_test $(pyver) $(workdir) .
    displayName: REST API tests
