# File: jobs/build.yml

parameters:
  name: ''
  pyver: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: 'ubuntu-16.04'
  container: conan_tests
  steps:
  - script: whoami
  - script: python $(runner) $(module) $(parameters.pyver) $(sourcedir) $(workdir) -e rest_api --num_cores=$(num_cores) --server_api=$(api_conf) -f $(flavor)
